### ISSUE TITLE
Clarification on term “unlinkable”

### ISSUE THREAD

**Issue by bdetwiler** [bdetwiler/draft-detecting-unwanted-location-trackers#10]
From Eric Rescorla <[ekr@rtfm.com](mailto:ekr@rtfm.com)>, Thu, 04 May 2023 00:05 UTC
via [unwanted-trackers-request@ietf.org](mailto:unwanted-trackers-request@ietf.org)

S 3.5.
>   The address MUST be private and it MUST rotate periodically and be
>   unlinkable; otherwise, if the same address is used for long periods
>   of time, an adversary may be able to track a legitimate person from
>   carrying the accessory.

Unlinkable to who? You say below that you might use a PRF so it's
linkable by the paired accessory right}?

**Comment by tfpauly** [comment]
Agreed — perhaps it would be clearer to describe the randomness requirements as opposed to calling it broadly "unlinkable"?

**Comment by yannick-sierra** [comment]
I think the intent is for the addresses to be unlinkable by all but the owner devices, who need a way to recognize their own accessories. Agreed this could be made clearer.

**Comment by siddikaparlak** [comment]
This is clarified in the latest version hence closing this issue.
