### ISSUE TITLE
IANA registry

### ISSUE THREAD

**Issue by bdetwiler** [bdetwiler/draft-detecting-unwanted-location-trackers#15]
From Eric Rescorla <[ekr@rtfm.com](mailto:ekr@rtfm.com)>, Sun, 07 May 2023 20:06 UTC
via [unwanted-trackers-request@ietf.org](mailto:unwanted-trackers-request@ietf.org)

"Section 9 creates an IANA registry, but as a general matter, an I-D does
not
create registries and Independent Stream documents cannot do so except
in exceptional cases [0].

[0]
https://datatracker.ietf.org/doc/html/rfc8726#name-creating-new-iana-registrie"

**Comment by tfpauly** [comment]
If this goes on standards track at some point, then keeping the IANA considerations would be fine. Let's see where this lands first.
