### ISSUE TITLE
Pairing and pairing registry

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#17]
// originally from josselin=[40life360.com@dmarc.ietf.org](mailto:40life360.com@dmarc.ietf.org) on May 11th, 2023
// via [unwanted-trackers@ietf.org](mailto:unwanted-trackers@ietf.org)

1: Pairing

The word "Pairing" is used in various places of the draft and it seems for different meanings. I recommend using "BLE Pairing" to describe the actual BLE Pairing and avoid using the word "Pairing" for other uses. 

For instance, the following paragraph:
3.15.  Pairing registry

   Verifiable identity information of the owner of an accessory at time
   of pairing SHALL be recorded and associated with the serial number of
   the accessory, e.g., phone number, email address.

Should be replaced with something like:

3.15. Owner registry

Verifiable identity information of the owner of an accessory at time of association SHALL be...

**Comment by zaeddinger** [comment]
Hi Josselin,

Re: 1 (Pairing) - that seems like a good update. Do you want to submit a pull request with the places you’d like to update that language? Else we can take a pass through in the next round of updates.

**Comment by josselindlb** [comment]
Yes, I'll prepare a PR

**Comment by josselindlb** [comment]
I created a branch with the related changes, could I get permission to push it so I can create a PR?

**Comment by josselindlb** [comment]
Can you please help with push access @bdetwiler ?
