### ISSUE TITLE
Advertising interval

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#19]
// originally from josselin=40life360.com@dmarc.ietf.org on May 11th, 2023
// via unwanted-trackers@ietf.org

3: Advertising Interval

The advertising Interval requirements in 3.9:

There is no justification to constraint devices to these advertising intervals so the requirement should be removed.

**Comment by josselindlb** [comment]
Agreed to not provide a lower bound limit.

About upper bound:
Our understanding is that time to discover or time to connect connect increase linearly with the advertising interval at close to medium range and staying under 4 seconds provides acceptable latencies for item trackers.
In the scope of this spec, close to medium range could be assumed and thus a 4s seconds limit could be used. Interested to hear about potential different findings on this.
