### ISSUE TITLE
Availability for law enforcement

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#20]
// Originally from alexis@eff.org on May 15th, 2023
// via unwanted-trackers@ietf.org

''''
3.15.3.  Availability for law enforcement

  The pairing registry SHALL be made available to law enforcement upon
  a valid law enforcement request.
''''

Since this a protocol for how a location tracker should behave for proper detection, this section is out of scope. This appears to dictate on what should happen with law enforcement access on what happens *after detection*, thus the protocol completing it's task and afterwards the user deciding on whatever action to take.

I anticipate language about law enforcement would appear somewhere in the usage of user establishing a tracker for use (benign or malicious), but strongly suggest addressing law enforcement access should be stricken from the scope of the specification.

**Comment by zoracon** [comment]
Just leaving a note here that there will be a follow up to this to possibly offer language on law enforcement requests.

**Comment by zoracon** [comment]
Here is the updated text proposed for law enforcement. So yes, this is in conflict with my previous statement but I was willing to draw it back after a conversation with my colleagues.

"Additionally, unwanted physical trackers should be accountable. Manufacturers should store the bare minimum of information about the phone or account that the tracker is paired to, and they should store it for a time and in a manner consistent with their data retention policies. The information should be made available to others only in response to a valid court order."
