### ISSUE TITLE
Supporting active scanning for unwanted tracking

### ISSUE THREAD

**Issue by maggiedelano** [bdetwiler/draft-detecting-unwanted-location-trackers#36]
Thanks for your work on this document, and for soliciting feedback.

I did some research on Apple AirTags last year, and one of the things that surprised me was how difficult it was to detect an AirTag using a [standard bluetooth scanner](https://www.maggiedelano.com/2022/02/21/apple-airtags-active-scanning.html) on iOS. It was much easier on Android, and unless it has changed recently there is no way to actively scan for AirTags on iOS (although it was in a beta at some point?). There are many contexts where a user would prefer to be able to actively scan their environment for unwanted trackers, rather than relying on a passive notification (which can take hours to occur).

I understand that platform issues are out of scope for this document, so I'll focus my other comments more specifically here too. Could the authors share the above concerns/suggestions with the relevant iOS team?

This document proposes an advertisement payload (section 3.4) that would allow "platforms to easily scan for and detect the location-enabled Bluetooth advertisement" (section 3.6). From what I can tell this is close to what AirTags already do. A few questions/comments:

- Will the service data TLV be standardized across location trackers? (I'm assuming yes but part of that section is marked TODO)
- It would be helpful to have some context on what existing location trackers already do and how/whether this is codification of what existing trackers e.g. AirTags already do, vs. a new proposed advertisement packet. I think the existing one works fine but the iOS platform is an issue for active scanning right now as I discuss above.
- I think section 6 should encourage (if not require) platforms to support both active and passive scanning. There should also be some discussion about appropriate time frames for passive notification (getting notified hours later is not helpful, but at the same time false positives need to be avoided).

**Comment by siddikaparlak** [comment]
Thanks for your feedback.

Yes, the service data TLV will be standardized as explained in the latest version.

This draft focuses on the practices and protocols to enable the detection of unwanted trackers. Implementing or providing tools for active scanning is a choice up to the platforms and not in the scope of this draft.
