### ISSUE TITLE
Charter: Not having access to a phone is a concern

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#51]
Not having access to a phone is a concern. Brought up by Ted Hardie.

**Comment by dkg** [comment]
no access to a phone is a concern in several different directions:

- A modern, up-to-date, well-maintained mobile device can be expensive, and is not necessarily available to everyone who wants one.
- A person who is the target of stalking or other abusive surveillance may have a (not unreasonable) concern that their phone is itself compromised to spy on them, so they might not want to carry it with them everywhere.  If they leave it behind, how can they then detect conformant unwanted trackers?
- When anyone wants to temporarily disable their own phone (or loses it, or runs out of battery, or they turn off bluetooth to conserve battery, etc), their own paired bluetooth devices will switch to "separated" mode, which is easier for a network of detectors to track than "near-owner" mode.
- It's also a problem in terms of false alerts: temporarily disabled phone → "separated" mode peripherals → warnings for anyone traveling with the person whose phone is off.
