### ISSUE TITLE
Charter: tracking network is the source of the problem 

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#54]
Tracking network is the source of the problem as stated by several people in BoF meeting. Request to expand scope of charter to include this

**Comment by ekr** [comment]
This is related to #47, because the point is that the existence of the tracking network is what creates the risk of misuse of the trackers, and especially of nonconformance.

**Comment by cfossace** [comment]
Would "unregistered" trackers be considered nonconformant? I think this addresses my issue on endpoint validation #31

**Comment by ekr** [comment]
That's one way to be nonconformant, but you might imagine registering a tracker and then using its keying material with a nonconformant device.

**Comment by zaeddinger** [comment]
Since this thread we've made updates in PR #72 and PR #83 -- but if there are any more edits needed, please re-open.
