### ISSUE TITLE
Charter: obvious subversion of key rolling, hacked accessories, putting in worse info from privacy POV into payload

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#58]
Obvious subversion of key rolling, hacked accessories, putting in worse info from privacy POV into payload, etc. is detectable needs to be in scope. Tommy Pauly and Sam Weiler mentioned this.

**Comment by zaeddinger** [comment]
Appears that PR #72 addresses this as well - will close for now and can re-open if we want to add more.
