### ISSUE TITLE
Charter: Wasn’t clear that mechanisms to disable trackers are in or out of scope.

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#61]
Wasn’t clear that mechanisms to disable trackers are in or out of scope.

**Comment by dkg** [comment]
not clear what "disable" means here -- during the BoF, there was discussion about how Tile trackers can have this particular protocol disabled by their owner (making them directly non-conformant).  but you could also imagine the victim of unwanted tracking looking for a protocol-defined way to disable the device entirely when it is discovered.

The other question is whether it is possible for the device owner to disable some subset of capabilities of any given tracker (e.g. putting chewing gum in the speaker that is expected to make a audible alert when triggered).  Should the charter attempt to address or at least enumerate these risks, and what the implications are for the efficacy of this protocol?

**Comment by zaeddinger** [comment]
Closing with PR #75
