### ISSUE TITLE
IETF is a Standards Body and not a Regulatory Body

### ISSUE THREAD

**Issue by cfossace** [bdetwiler/draft-detecting-unwanted-location-trackers#93]
One thing I think that is important to point out is that the IETF is a standards body and not a regulatory. Body. This means that the standards we are creating are a recommendation at most.  It is currently relatively easy to create a tracker that will be nonconformant to the exisiting protocol, so I think we need to make sure that nonconformant trackers are not supported by the protocol, and will not be able to benefit from the protocol, since there is no regulatory body that would be able to enforce the standard we implement.

**Comment by zaeddinger** [comment]
Agreed that IETF is not a regulatory body :)

I believe item 5 in the program of work partially addresses this:
_Design mechanisms to ensure that devices that do not correctly implement or adhere to the DULT protocol can be detected and excluded from being trackable via crowdsourced location networks._

We could include in the scope the option to address the non-technical aspects (e.g., providing correct instructions on how to disable the tracker) in a solution. 

I also assume that there are other standards that have a similar issue -- wonder if there's a good example of how others have figured out how to handle this.

**Comment by tfpauly** [comment]
It seems that proposed charter is trying to focus on having technical ways to prevent non-conformant devices from participating, which is I believe the right approach, and also inline with @cfossace's comment (that these are technical standards not regulatory goals).

**Comment by cfossace** [comment]
So, one way to make sure that items that are non-conformant do not benefit from the protocol is doing endpoint authorization. https://petsymposium.org/popets/2023/popets-2023-0006.pdf

The authors would be happy to discuss this. The authorization would still be privacy preserving.
